language: node_js
node_js:
  - "8"
  - "10"

before_instal:
  - npm i -g npm@5.6.0

install:
  - npm install -g codecov
  - npm install istanbul
  - npm install

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
  - codecov
  - bash <(curl -s https://codecov.io/bash)
  - npm run build

branches:
  only:
    - dev
